version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: dev-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supersecret
      MONGO_DB_NAME: mydb
      MONGO_APP_USER: appuser
      MONGO_APP_PASS: apppass
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: node:20-alpine
    container_name: dev-backend
    working_dir: /app
    env_file: .env
    environment:
      MONGODB_URI: mongodb://appuser:apppass@mongo:27017/mydb?authSource=admin
      PORT: 3001
      SWAGGER_ENABLED: "true"
    command: sh -c "corepack enable && pnpm install && pnpm run start:dev"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - pnpm_store:/root/.pnpm-store
    ports:
      - "3001:3001"
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    image: node:20-alpine
    container_name: dev-frontend
    working_dir: /app
    environment:
      PORT: 3000
      NUXT_PORT: 3000
      NUXT_HOST: 0.0.0.0
      NUXT_PUBLIC_API_BASE: "/api"
    # Expose Nuxt on network; proxy /api to backend service
    command: sh -c "corepack enable && pnpm install && pnpm run dev -- -p 3000 --host 0.0.0.0"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - pnpm_store:/root/.pnpm-store
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
  frontend_node_modules:
  backend_node_modules:
  pnpm_store: